AmerProba/Models/ErrorViewModel.cs
using System;

namespace AmerProba.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AmerProba/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AmerProba.Models;

namespace AmerProba.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AmerProba/Controllers/TransakcijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AmerProba.Data;
using Microsoft.AspNetCore.Identity;

namespace AmerProba.Controllers
{
    public class TransakcijaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TransakcijaController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Transakcija
        public async Task<IActionResult> Index()
        {

            //var userId = int.Parse(_userManager.GetUserId(User));
            var userId = (_userManager.GetUserId(User));
            ViewBag.UserID = userId;
            List<Transakcija> TrLista =new List<Transakcija>();
            foreach (var tr in _context.Transakcije)
            {
                if(tr.KorisnikId==userId)
                    TrLista.Add(tr);
            }
            return View(TrLista);
            //return View(await _context.Transakcije.ToListAsync());
        }

        // GET: Transakcija/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transakcija = await _context.Transakcije
                .FirstOrDefaultAsync(m => m.TransakcijaId == id);
            if (transakcija == null)
            {
                return NotFound();
            }

            return View(transakcija);
        }

        // GET: Transakcija/Create
        public IActionResult Create()
        {
            var userId = (_userManager.GetUserId(User));
            ViewBag.UserID = userId;

            var selectListaTipoviTransakcija = Enum.GetValues(typeof(TipTransakcije))
                .Cast<TipTransakcije>()
                .Select(tt => new SelectionListItem
                {
                    Value = ((int)tt).ToString(),
                    Text = tt.ToString()
                });
            ViewBag.TipTransakcije = new SelectList(selectListaTipoviTransakcija, "Value", "Text");
            //var selectListaSpisakKorisnika = new List<User>().Select(tt=> new SelectListItem
            //    {
            //        Value = tt.Id,
            //        Text = tt.UserName
            //    });
               
            //ViewBag.SpisakKorisnika = new SelectList(selectListaSpisakKorisnika, "Value", "Text");
            return View();
        }

        // POST: Transakcija/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TransakcijaId,Tip,Detalji,Iznos,Vrijeme,KorisnikId")] Transakcija transakcija)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transakcija);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(transakcija);
        }

        // GET: Transakcija/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transakcija = await _context.Transakcije.FindAsync(id);
            if (transakcija == null)
            {
                return NotFound();
            }
            var selectListaTipoviTransakcija = Enum.GetValues(typeof(TipTransakcije))
                .Cast<TipTransakcije>()
                .Select(tt => new SelectionListItem
                {
                    Value = ((int)tt).ToString(),
                    Text = tt.ToString()
                });
            ViewBag.TipTransakcije = new SelectList(selectListaTipoviTransakcija, "Value", "Text");
            return View(transakcija);
        }

        // POST: Transakcija/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TransakcijaId,Tip,Detalji,Iznos,Vrijeme,KorisnikId")] Transakcija transakcija)
        {
            if (id != transakcija.TransakcijaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transakcija);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransakcijaExists(transakcija.TransakcijaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(transakcija);
        }

        // GET: Transakcija/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transakcija = await _context.Transakcije
                .FirstOrDefaultAsync(m => m.TransakcijaId == id);
            if (transakcija == null)
            {
                return NotFound();
            }

            return View(transakcija);
        }

        // POST: Transakcija/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transakcija = await _context.Transakcije.FindAsync(id);
            _context.Transakcije.Remove(transakcija);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransakcijaExists(int id)
        {
            return _context.Transakcije.Any(e => e.TransakcijaId == id);
        }
    }
}

AmerProba/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AmerProba/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AmerProba/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

AmerProba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AmerProba</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AmerProba</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Transakcija" asp-action="Index">Transakcije</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AmerProba</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

AmerProba/Views/Transakcija/Create.cshtml
@model AmerProba.Data.Transakcija

@{
    ViewData["Title"] = "Create";
}
@if (ViewBag.UserID == null)
{
    <h2>Please log in to see your transactions!</h2>
}
else
{
<h2>Create</h2>

<h4>Transakcija</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Tip" class="control-label"></label>
                <select asp-for="Tip" asp-items="@ViewBag.TipTransakcije" class="form-control"></select>
                <span asp-validation-for="Tip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detalji" class="control-label"></label>
                <input asp-for="Detalji" class="form-control" />
                <span asp-validation-for="Detalji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Iznos" class="control-label"></label>
                <input asp-for="Iznos" class="form-control" />
                <span asp-validation-for="Iznos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrijeme" class="control-label"></label>
                <input asp-for="Vrijeme" class="form-control" />
                <span asp-validation-for="Vrijeme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KorisnikId" class="control-label"></label>
                <input asp-for="KorisnikId" class="form-control" value="@ViewBag.UserID" disabled />
                @*<select asp-for="KorisnikId" asp-items="@ViewBag.SpisakKorisnika" class=" form-control"></select>*@
                <span asp-validation-for="KorisnikId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AmerProba/Views/Transakcija/Delete.cshtml
@model AmerProba.Data.Transakcija

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transakcija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Detalji)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Detalji)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Iznos)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Iznos)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KorisnikId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KorisnikId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TransakcijaId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AmerProba/Views/Transakcija/Details.cshtml
@model AmerProba.Data.Transakcija

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Transakcija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Detalji)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Detalji)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Iznos)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Iznos)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KorisnikId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KorisnikId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TransakcijaId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AmerProba/Views/Transakcija/Edit.cshtml
@model AmerProba.Data.Transakcija

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Transakcija</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TransakcijaId" />
            <div class="form-group">
                <label asp-for="Tip" class="control-label"></label>
                <select asp-for="Tip" asp-items="@ViewBag.TipTransakcije" class="form-control"></select>
                <span asp-validation-for="Tip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Detalji" class="control-label"></label>
                <input asp-for="Detalji" class="form-control" />
                <span asp-validation-for="Detalji" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Iznos" class="control-label"></label>
                <input asp-for="Iznos" class="form-control" />
                <span asp-validation-for="Iznos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrijeme" class="control-label"></label>
                <input asp-for="Vrijeme" class="form-control" />
                <span asp-validation-for="Vrijeme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KorisnikId" class="control-label"></label>
                <input asp-for="KorisnikId" class="form-control" disabled />
                <span asp-validation-for="KorisnikId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AmerProba/Views/Transakcija/Index.cshtml
@model IEnumerable<AmerProba.Data.Transakcija>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Detalji)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Iznos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vrijeme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KorisnikId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Detalji)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Iznos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vrijeme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KorisnikId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TransakcijaId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.TransakcijaId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.TransakcijaId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>